name: Terraform Plan Summary for Pull Requests
description: Run plan and reports it on a comment in a pull request.

inputs:
  working-directory:
    description: Directory where Terraform code is located.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Terraform Plan
      id: plan
      uses: luiz-patire-vigil/actions-test/.github/actions/terraform-plan@main
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Delete Old Bot Comments
      uses: actions/github-script@v7
      with:
        script: |
          const author = 'github-actions[bot]';
          const currentSha = process.env.GITHUB_SHA;
          
          // List all comments
          const { data: comments } = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          // Filter out comments made by the bot and delete them
          const botCommentsToDelete = comments.filter(comment => {
            if (comment.user.login !== author) return false;
            const match = comment.body?.match(/\[bot-tag\]: action-data sha=(\w{7,40})/);
            return match && match[1] !== currentSha;
          });
          
          for (const comment of botCommentsToDelete) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id,
            });
          }

    - name: Comment on Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const currentSha = process.env.GITHUB_SHA;

          const output = `
          ### Terraform plan for ${{ inputs.working-directory }}

          <!-- github-action-data sha=${currentSha} -->

          <details><summary>Show Plan</summary>
 
          \`\`\`\n
          ${{ steps.plan.outputs.plan }}
          \`\`\`
 
          </details>
          
          [bot-tag]: action-data sha=${currentSha}`;
 
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
