name: Terraform Plan Summary for Pull Requests
description: Run plan and reports it on a comment in a pull request

inputs:
  working-directory:
    description: Directory where Terraform code is located
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      id: plan
      uses: luiz-patire-vigil/actions-test/.github/actions/terraform-plan@main
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Comment on Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const output = `
          ### Terraform plan for ${{ inputs.working-directory }}

          <details><summary>Show Plan</summary>
 
          \`\`\`\n
          ${{ steps.plan.outputs.stdout }}
          \`\`\`
 
          </details>`;
 
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
