name: Terraform Init
description: Composite action to checkout code and run Terraform init

# permissions:
#   id-token: write
#   contents: read

inputs:
  working-directory:
    description: Directory where Terraform code is located
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} plan