name: Terraform Init
description: Composite action to checkout code and run Terraform init

inputs:
  working-directory:
    description: Directory where Terraform code is located
    required: false
    default: .

  aws-role-to-assume:
    description: AWS Role to assume. Required for OIDC.
    required: false

  aws-region:
    description: AWS Region (for backend and provider)
    required: false

  aws-access-key-id:
    description: AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
    required: false

  aws-secret-access-key:
    description: AWS Secret Access Key. Required if aws-access-key-id is provided.
    required: false

  modules-private-keys:
    description: AWS Region (for backend and provider)
    required: false
    default: null

runs:
  using: "composite"
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-session-name: github-oidc
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform Modules Private Keys
      if: ${{ inputs.modules-private-keys != '' && inputs.modules-private-keys != null }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ inputs.modules-private-keys }}

    - name: Terraform Init
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} init -input=false

    - name: Terraform Format
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} fmt -check -recursive

    - name: Terraform Validate
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} validate
