name: Terraform Apply
description: Run Terraform apply.

inputs:
  working-directory:
    description: Directory where Terraform code is located.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Terraform Apply
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} apply -auto-approve
