name: Terraform Plan
description: Composite action to run Terraform plant, giving it as an output.

# Workflows using this action need the following permissions:
# permissions:
#   issues: write
#   pull-requests: write

inputs:
  working-directory:
    description: Directory where Terraform code is located.
    required: false
    default: .

outputs:
  plan:
    description: Modified directories.
    value: ${{ steps.tf-plan.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      id: tf-plan
      shell: bash
      run: |
        terraform -chdir=${{ inputs.working-directory }} plan -no-color
