name: Detect Changes
description: Detect changes in Terraform files within the directory tree, returning the directory list.

inputs:
  base-ref:
    required: false
    type: string
    default: origin/main

  merge-ref:
    required: false
    type: string
    default: HEAD

outputs:
  dirs:
    description: Modified directories.
    value: ${{ steps.check-dirs.outputs.dirs }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check modified directories
      id: check-dirs
      shell: bash
      run: |
        echo "Detecting modified directories"
        changed_files=$(git diff --name-only ${{ inputs.base-ref }}...${{ inputs.merge-ref }})
        echo "Changed files detected:"
        echo "$changed_files"

        tf_files=$(echo "$changed_files" | grep -E '\.tf$|\.tfvars$' || true)

        if [ -z "$tf_files" ]; then
          echo "No Terraform-related files changed."
          echo "dirs=[]" >> $GITHUB_OUTPUT
        else
          folders=$(echo "$tf_files" \
            | xargs -n1 dirname \
            | sort -u \
            | jq -R . \
            | jq -sc .)
          echo "Changed dirs detected: $folders"
          echo "dirs=$folders" >> $GITHUB_OUTPUT
        fi
