name: Terraform plan on PR

# Workflows calling this workflow should set
# permissions:
#   id-token: write
#   contents: read
#   issues: write
#   pull-requests: write

on:
  workflow_call:
    inputs:
      dir-list:
        description: Comma-separated list of directories to check. If empty, detect changes.
        required: false
        type: string
        default: ""

    secrets:
      aws-role-to-assume:
        description: AWS Role to assume. Required for OIDC.
        required: false

      aws-region:
        description: AWS Region (for backend and provider).
        required: false

      aws-access-key-id:
        description: AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
        required: false

      aws-secret-access-key:
        description: AWS Secret Access Key. Required if aws-access-key-id is provided.
        required: false

      modules-private-keys:
        description: Private key for TF to access the one-terraform-modules repository. 
        required: false

permissions:
  # these are needed for terraform-init
  id-token: write
  contents: read
  # thses are needed for terraform-plan-summary-for-pr
  issues: write
  pull-requests: write

jobs:
  set-working-directory-values:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.parse-input.outputs.dirs }}
    steps:
      - name: Parse input directories
        id: parse-input
        uses: luiz-patire-vigil/actions-test/.github/actions/terraform-parse-directory-input@main
        with:
          dir-list: ${{ inputs.dir-list }}

  plan-report:
    needs: set-working-directory-values
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: ${{ fromJson(needs.set-working-directory-values.outputs.dirs) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: luiz-patire-vigil/actions-test/.github/actions/terraform-init@main
        with:
          working-directory: ${{ matrix.working-directory }}
          aws-role-to-assume: ${{ secrets.aws-role-to-assume || null}}
          aws-access-key-id: ${{ secrets.aws-access-key-id || null}}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key || null}}
          aws-region: ${{ secrets.aws-region }}
          modules-private-keys : ${{ secrets.modules-private-keys }}

      - name: Create Plan Report on PR
        uses: luiz-patire-vigil/actions-test/.github/actions/terraform-plan-summary-for-pr@main
        with:
          working-directory: ${{ matrix.working-directory }}
