name: Validate Terraform on Push

on:
  workflow_call:
    inputs:
      dirs:
        description: "Comma-separated list of directories to check. If empty, detect changes."
        required: false
        type: string
        default: ''

    secrets:
      aws-role-to-assume:
        description: AWS Role to assume. Required for OIDC.
        required: false

      aws-region:
        description: AWS Region (for backend and provider)
        required: false

      aws-access-key-id:
        description: AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
        required: false

      aws-secret-access-key:
        description: AWS Secret Access Key. Required if aws-access-key-id is provided.
        required: false

      modules-private-keys:
        description: AWS Region (for backend and provider)
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  set-working-directory-values:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.set-input.outputs.dirs || steps.detect-changes.outputs.dirs }}
    steps:
      - name: Use input directories
        id: set-input
        if: ${{ inputs.dirs != '' }}
        run: |
          echo "Processing input directories: ${{ inputs.dirs }}"

          # Convert comma-separated to array, trim whitespace
          IFS=',' read -ra DIRS <<< "${{ inputs.dirs }}"
          CLEAN_DIRS=()
          for dir in "${DIRS[@]}"; do
            clean_dir="${dir#"${dir%%[![:space:]]*}"}"  # trim leading
            clean_dir="${clean_dir%"${clean_dir##*[![:space:]]}"}"  # trim trailing

            if [ -n "$clean_dir" ]; then
              CLEAN_DIRS+=("$clean_dir")
            fi
          done

          # Build compact JSON array safely
          dirs_json=$(printf '%s\n' "${CLEAN_DIRS[@]}" | jq -R . | jq -s -c .)
          echo "Converted directories to JSON (no line breaks): $dirs_json"

          echo "directories=$dirs_json" >> $GITHUB_OUTPUT

      - name: Detect changed directories (fallback)
        id: detect-changes
        if: ${{ inputs.dirs == '' }}
        uses: luiz-patire-vigil/actions-test/.github/actions/detect-terraform-changes@main

  validate:
    runs-on: ubuntu-latest
    needs: set-working-directory-values
    strategy:
      matrix:
        working-directory: ${{ fromJson(needs.set-working-directory-values.outputs.dirs) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: luiz-patire-vigil/actions-test/.github/actions/terraform-init@main
        with:
          working-directory: ${{ matrix.working-directory }}
          aws-role-to-assume: ${{ secrets.aws-role-to-assume || null}}
          aws-access-key-id: ${{ secrets.aws-access-key-id || null}}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key || null}}
          aws-region: ${{ secrets.aws-region }}
          modules-private-keys : ${{ secrets.modules-private-keys }}

      - uses: luiz-patire-vigil/actions-test/.github/actions/terraform-plan@main
        with:
          working-directory: ${{ matrix.working-directory }}
