name: Terraform Validate
description: Composite action to check Terraform format and run validate.

inputs:
  working-directory:
    description: Directory where Terraform code is located.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Terraform Format
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} fmt -check -recursive

    - name: Terraform Validate
      shell: bash
      run: terraform -chdir=${{ inputs.working-directory }} validate
